config/routes.rb
Rails.application.routes.draw do

  resources :tactic_covers
  root 'dashboard#index'

  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }

  resources :calllists  do
    collection do
      get :export
      post :read_from_excel
      post :save_from_json
      get :load_note_options
      get :load_date_options
      get :load_batch_options
    end
  end

  resources :call_analyse_savers do
    collection do
      get :default
    end
  end

  resources :cases do
    collection do
      get :search
    end
  end

  resources :dashboard

  resources :extra_tasks do
    member do
      get :jump_to_execute
      get :jump_to_show
      get :jump_to_bind
    end
  end

  resources :image_views, only: [:index]

  resources :position_decisions

  resources :resources do
    collection do
      get :search
    end
  end

  resources :suspects

  resources :suspects_teams

  resources :tactics do
    member do
      get :get_tactic_tasks
      post :persist_tasks
      get :progress
      get :edit_covers
    end
  end

  resources :tactic_tasks

  resources :tools do
    collection do
      get :home
      get :add_info
      get :add_manual
      get :rlat
      get :rlat_details
    end
  end

  post 'users/search', to: 'users/users#search'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/call_analyse_saver.rb
class CallAnalyseSaver < ApplicationRecord
  belongs_to :user

  COLUMNS_ON_EXTRA_TASK = {
    id: "ID",
    title: "标题",
    created_at: "创建时间",
  }
  EXECUTE_PATH = "/tools/home"
  SEARCH_KEY = :title

end

app/models/calllist.rb
require 'roo'

class Calllist < ApplicationRecord

  #从文件读取数据,不作处理直接返回json
  def self.read(file)
    spread_sheets = Roo::Spreadsheet.open(file)
    sheets_names = spread_sheets.sheets
    sheets = sheets_names.map{|name| {:name=>name,:rows => spread_sheets.sheet(name).map{|rows| rows}}}
    #[{:name=>"name",:rows=>[[row]...],[],[]]
    return sheets
  end

end

app/models/case.rb
class Case < ApplicationRecord
  has_and_belongs_to_many :tactics
end

app/models/extra_task.rb
class ExtraTask < ApplicationRecord
  belongs_to :tactic_task

  TASK_MAP = {
    "话单分析": CallAnalyseSaver
  }
end

app/models/suspect.rb
class Suspect < ApplicationRecord
end

app/models/suspects_team.rb
class SuspectsTeam < ApplicationRecord
end

app/models/tactic.rb
class Tactic < ApplicationRecord
  has_and_belongs_to_many :cases
  accepts_nested_attributes_for :cases, allow_destroy: true
  has_many :tactic_tasks ,dependent:  :destroy
  has_and_belongs_to_many :tactic_covers

  def finished_task_count
    return self.tactic_tasks.where(:status => "已完成").size
  end

  def unfinished_task_count
    return self.tactic_tasks.where.not(:status => "已完成").size
  end

  def has_finish?
    return self.status == "已完成" && self.unfinished_task_count == 0
  end
end

app/models/tactic_category.rb
class TacticCategory < ApplicationRecord
end

app/models/tactic_cover.rb
class TacticCover < ApplicationRecord
  has_and_belongs_to_many :tactic
end

app/models/tactic_task.rb
class TacticTask < ApplicationRecord
  belongs_to :tactic
  has_and_belongs_to_many :user
  has_one :extra_task, dependent: :destroy

  after_create :create_extra_task

  LIST_OF_EXTRA_TASK = ["话单分析"]

  def should_do_extra_task
    return self.extra_task.present?
  end

  private
    def create_extra_task
      if LIST_OF_EXTRA_TASK.include?(self.category)
        self.create_extra_task!(:name => self.category)
      end
    end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, #:registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_and_belongs_to_many :tactic_task
end

app/controllers/tools_controller.rb
class ToolsController < ApplicationController

  def index
  end
  #首页
  def home
    @tools_type = "home"
    @cas_of_user=CallAnalyseSaver.where(:user_id=>current_user.id).order("created_at desc").limit(6)
  end
  #新增情报资料库
  def add_info
    @tools_type = "home"
  end
  #手工导入
  def add_manual
    @tools_type = "home"
  end
  #人际交往关系
  def rlat
    @tools_type = "rlat"
  end
  #人际交往关系详细
  def rlat_details
    @tools_type = "rlat"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/calllists_helper.rb
module CalllistsHelper
end

app/helpers/cases_helper.rb
module CasesHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/excel_helper.rb
module ExcelHelper
end

app/helpers/resources_helper.rb
module ResourcesHelper
end

app/helpers/suspects_helper.rb
module SuspectsHelper
end

app/helpers/tactics_helper.rb
module TacticsHelper
end

app/helpers/tools_helper.rb
module ToolsHelper
end

app/views/tools/_leftside.html.erb
<div class="left-side left-side-inverse column-18">
		<div class="left-side-heading">
			<div class="heading-title">
				<a class="pull-right small" href="<%= root_path %>">回首页</a>
				分类
			</div>
			<div class="input-group">
				<input type="text" class="form-control" value="搜索">
				<span class="input-group-btn">
					<button class="btn btn-primary" type="button">
					搜
					</button>
				</span>
			</div>
		</div>
		<div class="left-side-btn-menu">
			<a href="<%= home_tools_path %>" class="btn btn-normal btn-block <% if @tools_type == "home" %>active<% end %>" type="button">全部分类</a>
			<a href="<%= rlat_tools_path %>" class="btn btn-normal btn-block <% if @tools_type == 'rlat' %>active<% end %>" type="button">人际交往报告(10)</a>
			<a href="" class="btn btn-normal btn-block" type="button">出行轨迹报告(10)</a>
			<a href="" class="btn btn-normal btn-block" type="button">资金流转报告(10)</a>
			<a href="" class="btn btn-normal btn-block" type="button">物流往来报告(10)</a>
			<a href="" class="btn btn-normal btn-block" type="button">消费情况报告(9)</a>
			<a href="" class="btn btn-normal btn-block" type="button">人员只能画像(8)</a>
			<a href="" class="btn btn-normal btn-block" type="button">其他(9)</a>
		</div>
	</div>

app/views/tools/_main.html.erb
<div class="tools_main">
	<div class="panel panel-default">
		<div class="panel-heading">
			<div class="panel-title row">
				<div class="col-xs-8">
					<label href="#">滚轮操作</label>
					<div class="btn-group btn-group-xs" role="group" aria-label="...">
						<button type="button" class="btn btn-default wheel-setter" data-behavior="scroll">平移</button>
						<button type="button" class="btn btn-default wheel-setter" data-behavior="zoom">缩放</button>
					</div>
					<label href="#">缩放控制</label>
					<div class="btn-group btn-group-xs" role="group" aria-label="...">
						<button type="button" class="btn btn-default scale-setter" data-scale-type="+">放大</button>
						<button type="button" class="btn btn-default scale-setter" data-scale-type="-">缩小</button>
					</div>
					<label href="#">布局方式</label>
					<div class="btn-group btn-group-xs" role="group" aria-label="...">
						<button type="button" class="btn btn-default layout-setter" data-layout="grid">网格</button>
						<button type="button" class="btn btn-default layout-setter" data-layout="tree">树形</button>
						<button type="button" class="btn btn-default layout-setter" data-layout="layeredDigraph">层次</button>
						<button type="button" class="btn btn-default layout-setter" data-layout="forceDirected">力导向</button>
						<button type="button" class="btn btn-default layout-setter" data-layout="circular">圆形</button>
						<button type="button" class="btn btn-default layout-setter" data-layout="default">自由</button>
					</div>
				</div>
				<div class="col-xs-4 text-right">
					<form class="hidden" enctype="multipart/form-data">
						<input type="file" class="hidden" id="field-data-import"/>
					</form>
					<a class="btn btn-link btn-xs" id="btn-data-import"><span class="fa fa-camera-retro" aria-hidden="true"></span> 数据导入</a>
					<a class="btn btn-link btn-xs"  @click="showModal=true"><span class="glyphicon glyphicon-save" aria-hidden="true"></span> 数据保存</a>
					<a class="btn btn-link btn-xs" id="btn-image-export"><span class="glyphicon glyphicon-export" aria-hidden="true"></span> 导出图片</a>
				</div>
			</div>
		</div>
		<div class="panel-body" style="padding-bottom: 0px;">
			<div class="tab-content" style="width:100%;height:100%;overflow:auto;">
				<div role="tabpanel" class="tab-pane in active" id="tab_main_diagram_1" style="width:100%;height:100%">
					<div id="tools_main_diagram" style="width:100%; height:100%"></div>
				</div>
			</div>
		</div>
	</div>
	<div>
		<modal v-show="showModal" @close="showModal = false" width="600px">
			<h3 slot="header">保存数据</h3>
			<div slot="body">
				<div class="form-group">
						<span class="il-blk"><input type="radio" name='save-location' value='local' data-labelauty="保存到本地"/></span>
						<span class="il-blk"><input type="radio" name='save-location' value='server-update' data-labelauty="更新服务器档案"/></span>
						<span class="il-blk"><input type="radio" name='save-location' value='server-new' checked data-labelauty="服务器另存新档"/></span>
				</div>
				<div id="div-save-title" class="form-group">
					<input id="text-save-title" type="text" class="form-control" placeholder="请输入存档名称"/>
				</div>
			</div>
			<div slot="footer">
				<button id="btn-data-save" class="btn btn-primary" @click="showModal=false">
					确定
				</button>
				<button class="btn btn-default" @click="showModal=false">
					取消
				</button>
			</div>
		</modal>
	</div>
</div>

app/views/tools/_new_analysis_part.html.erb
<div class="inner-panel-heading">
				<div class="panel-title">
					新建分析
				</div>
			</div>
			<div class="inner-panel-body">
				<div class="add-analysis-tool">
					<a class="add-analysis-item" href="<%= add_info_tools_path %>">
						<span class="aliconfont icon-relation"></span>
						<div class="mt5">通话关系</div>
					</a>
					<a class="add-analysis-item" href="">
						<span class="aliconfont icon-home"></span>
						<div class="mt5">银行交易</div>
					</a>
					<a class="add-analysis-item" href="">
						<span class="aliconfont icon-mony2"></span>
						<div class="mt5">资金流转</div>
					</a>
					<a class="add-analysis-item" href="">
						<span class="aliconfont icon-car2"></span>
						<div class="mt5">物流往来</div>
					</a>
					<a class="add-analysis-item" href="">
						<span class="aliconfont icon-mony"></span>
						<div class="mt5">消费情况</div>
					</a>
					<a class="add-analysis-item active" href="">
						<span class="aliconfont icon-person-pic"></span>
						<div class="mt5">人员画像</div>
					</a>
					<a class="add-analysis-item" href="">
						<span class="aliconfont icon-other"></span>
						<div class="mt5">其他</div>
					</a>
				</div>
			</div>

app/views/tools/add_info.html.erb
<div class="bread-nav-wrap">
	<ul class="bread-nav clearfix">
		<li class="bread-nav-item home">
			<a class="link-item" href="<%= root_path %>"><span class="glyphicon glyphicon-home"></span></a>
		</li>
		<li class="bread-nav-item">
			<a class="link-item" href="">分析工具</a>
		</li>
		<li class="bread-nav-item">
			<span class="link-item">新建分析</span>
		</li>
	</ul>
</div>
<!-- 路径导航 end -->
<%= render 'leftside', tools: @tools %>
<!-- left-side end -->
<div class="container-18">
	<div class="panel panel-default">
		<div class="inner-panel-heading">
			<div class="panel-title">
				新建分析
			</div>
		</div>
		<div class="inner-panel-body">
			<div class="row">
				<form action="" class="">
					<div class="col-xs-3">
						<label class="" for="">分析名称</label>
						<div class="mt5"><input class="form-control" type="text"></div>
					</div>
					<div class="col-xs-3">
						<label class="" for="">关联案件</label>
						<div class="mt5">
							<input class="form-control" type="text">
						</div>

					</div>
					<div class="col-xs-5">
						<label class="" for="">通话时间区间</label>
						<div class="input-group mt5">
							<input class="form-control" type="text">
							<span class="input-group-addon right-radius">
								<span class="glyphicon glyphicon-calendar text-primary"></span>
							</span>
							<span class="input-group-addon no-bd">
								到
							</span>
							<input class="form-control" type="text">
							<span class="input-group-addon">
								<span class="glyphicon glyphicon-calendar text-primary"></span>
							</span>
						</div>
					</div>
				</form>
			</div>
		</div>

		<div class="inner-panel-subheading">
			<span class="inner-panel-subtitle">分析类型</span>
		</div>
		<div class="inner-panel-body">
			<div class="add-analysis-tool">
				<a class="add-analysis-item" href="">
					<span class="aliconfont icon-relation"></span>
					<div class="mt5">通话关系</div>
				</a>
				<a class="add-analysis-item" href="">
					<span class="aliconfont icon-home"></span>
					<div class="mt5">银行交易</div>
				</a>
				<a class="add-analysis-item" href="">
					<span class="aliconfont icon-mony2"></span>
					<div class="mt5">资金流转</div>
				</a>
				<a class="add-analysis-item" href="">
					<span class="aliconfont icon-car2"></span>
					<div class="mt5">物流往来</div>
				</a>
				<a class="add-analysis-item" href="">
					<span class="aliconfont icon-mony"></span>
					<div class="mt5">消费情况</div>
				</a>
				<a class="add-analysis-item activ activee" href="">
					<span class="aliconfont icon-person-pic"></span>
					<div class="mt5">人员画像</div>
				</a>
				<a class="add-analysis-item" href="">
					<span class="aliconfont icon-other"></span>
					<div class="mt5">其他</div>
				</a>
			</div>
		</div>

		<div class="inner-panel-subheading">
			<span class="inner-panel-subtitle">数据导入</span>
		</div>
		<div class="inner-panel-body">
			<ul class="sub-nav clearfix">
				<li class="sub-nav-item">
					<a href="<%= add_manual_tools_path %>">手工导入</a>
				</li>
				<li class="sub-nav-item active">
					<a href="<%= add_info_tools_path %>">情报资料库</a>
				</li>
			</ul>
			<div id="data-screen-app">
				<div class="add-analysis-tool block-mt">
					<a class="add-analysis-item" href="javascript:void(0);">
						<span class="aliconfont icon-file2"></span>
						<div class="mt5">通话关系</div>
					</a>
					<a class="add-analysis-item" href="javascript:void(0);">
						<span class="aliconfont icon-msg"></span>
						<div class="mt5">银行交易</div>
					</a>
					<a class="add-analysis-item" href="javascript:void(0);">
						<span class="aliconfont icon-msg2"></span>
						<div class="mt5">资金流转</div>
					</a>
					<a class="add-analysis-item" href="javascript:void(0);">
						<span class="aliconfont icon-email"></span>
						<div class="mt5">物流往来</div>
					</a>
				</div>
				<div class="block-mt screen-analysis-data">
					<div class="col-sm-12">
						<div style="margin-left:-15px;">
							<span class="blk" style="margin:5px auto;">数据筛选:</span>
							<span class="il-blk"><input class="labelauty-small" type="checkbox" v-model="isNoteSelected" @change="loadOptions('note')" data-labelauty="备注"></span>
							<span class="il-blk"><input class="labelauty-small" type="checkbox" v-model="isDateSelected" @change="loadOptions('date')"  data-labelauty="日期"/></span>
							<span class="il-blk"><input class="labelauty-small" type="checkbox" v-model="isBatchSelected" @change="loadOptions('batch')" data-labelauty="批次"/></span>
						</div>
					</div>
					<div class="data-filter col-sm-4" v-if="isNoteSelected">
						<div class="col-sm-12">
							备注
						</div>
						<div class="col-sm-6">
							<select class="ca-multi-select" multiple @change="updateSelected($event,'noteSelected')">
								<option v-for="opt in noteOptions">{{opt}}</option>
							</select>
						</div>
						<div class="col-sm-6 ca-select-show" style="border: 1px solid lightgray;">
							<template v-for="sel in noteSelected">
								<span>{{sel}}</span><br/>
							</template>
						</div>
					</div>

					<div class="data-filter col-sm-4" v-if="isDateSelected">
						<div class="col-sm-12">
							日期
						</div>
						<div class="col-sm-6" >
							<select class="ca-multi-select" multiple @change="updateSelected($event,'dateSelected')">
								<option v-for="opt in dateOptions">{{opt}}</option>
							</select>
						</div>
						<div class="col-sm-6 ca-select-show" style="border: 1px solid lightgray;">
							<template v-for="sel in dateSelected">
								<span>{{sel}}</span><br/>
							</template>
						</div>
					</div>

					<div class="data-filter col-sm-4" v-if="isBatchSelected">
						<div class="col-sm-12">
							批次
						</div>
						<div class="col-sm-6" >
							<select class="ca-multi-select" multiple @change="updateSelected($event,'batchSelected')">
								<option v-for="opt in batchOptions">{{opt}}</option>
							</select>
						</div>
						<div class="col-sm-6 ca-select-show" style="border: 1px solid lightgray;">
							<template v-for="sel in batchSelected">
								<span>{{sel}}</span><br/>
							</template>
						</div>
					</div>

					<div class="clearfix"></div>
				</div>
				<div class="mt20">
					<%= link_to t('.confirm',:default => t("确定")) ,tools_path(:type=>:calllist,:sources=>'db'),{:class=>"btn btn-primary btn-long",:@click=>"setFilterData"} %>
					<%= link_to t('.cancel', :default => t("取消")),
					rlat_tools_path, :class => 'btn btn-default btn-long ml10' %>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/tools/add_manual.html.erb
<div class="bread-nav-wrap">
	<ul class="bread-nav clearfix">
		<li class="bread-nav-item home">
			<a class="link-item" href="<%= root_path %>"><span class="glyphicon glyphicon-home"></span></a>
		</li>
		<li class="bread-nav-item">
			<a class="link-item" href="<%= home_tools_path %>">分析工具</a>
		</li>
		<li class="bread-nav-item">
			<a class="link-item" href="">新建分析</a>
		</li>
		<li class="bread-nav-item">
			<span class="link-item">手工导入</span>
		</li>
	</ul>
</div>
<!-- 路径导航 end -->
<%= render 'leftside', tools: @tools %>
<!-- left-side end -->
<div class="container-18">
	<div class="panel panel-default clearfix">
		<div class="inner-panel-heading">
			<div class="panel-title">
				新建分析
			</div>
		</div>
		<div class="inner-panel-body">
			<div class="row">
				<form action="" class="">
					<div class="col-md-3">
						<label class="" for="">分析名称</label>
						<div class="mt5"><input class="form-control" type="text" value="张三通话分析"/></div>
					</div>
					<div class="col-md-3">
						<label class="" for="">关联案件</label>
						<div class="mt5">
							<input class="form-control" type="text" value="117走私案"/>
						</div>

					</div>
					<div class="col-md-5">
						<label class="" for="">通话时间区间</label>
						<div class="input-group mt5">
							<input class="form-control" type="text" value="2017-12-12"/>
							<span class="input-group-addon">
								<span class="glyphicon glyphicon-calendar text-primary"></span>
							</span>
							<span class="input-group-addon no-bd">
								到
							</span>
							<input class="form-control" type="text" value="2017-12-12"/>
							<span class="input-group-addon">
								<span class="glyphicon glyphicon-calendar text-primary"></span>
							</span>
						</div>


					</div>
				</form>
			</div>
		</div>

		<div class="inner-panel-subheading">
			<span class="inner-panel-subtitle">分析类型</span>
		</div>
		<div class="inner-panel-body">
			<div class="add-analysis-tool">
				<a class="add-analysis-item" href="">
					<span class="aliconfont icon-relation"></span>
					<div class="mt5">通话关系</div>
				</a>
				<a class="add-analysis-item" href="">
					<span class="aliconfont icon-home"></span>
					<div class="mt5">银行交易</div>
				</a>
				<a class="add-analysis-item" href="">
					<span class="aliconfont icon-mony2"></span>
					<div class="mt5">资金流转</div>
				</a>
				<a class="add-analysis-item" href="">
					<span class="aliconfont icon-car2"></span>
					<div class="mt5">物流往来</div>
				</a>
				<a class="add-analysis-item" href="">
					<span class="aliconfont icon-mony"></span>
					<div class="mt5">消费情况</div>
				</a>
				<a class="add-analysis-item" href="">
					<span class="aliconfont icon-person-pic"></span>
					<div class="mt5">人员画像</div>
				</a>
				<a class="add-analysis-item" href="">
					<span class="aliconfont icon-other"></span>
					<div class="mt5">其他</div>
				</a>
			</div>
		</div>


		<div class="inner-panel-subheading">
			<span class="inner-panel-subtitle">数据导入</span>
		</div>
		<div class="inner-panel-body" id="vue-excel-app">
			<ul class="sub-nav clearfix">
				<li class="sub-nav-item active">
					<a href="<%= add_manual_tools_path %>">手工导入</a>
				</li>
				<li class="sub-nav-item">
					<a href="<%= add_info_tools_path %>">情报资料库</a>
				</li>
			</ul>
			<form id = "read_from_excel" action="/calllists/process_excel" enctype="multipart/form-data" method="post">
				<div class="row block-mt">
					<div class="col-xs-3">
						<label for="">文件导入</label>
						<div class="input-group mt5">
							<input id='file_name_wrap' class="form-control" type="text" readonly="readonly" placeholder="请选择文件"/>
							<input id='upload_excel_field' class="hidden" name="excel_call_list" type="file" v-on:change="workbook.init()"/>
							<span class="input-group-addon" @click="showFileDialog">
								<span class="glyphicon glyphicon-folder-open text-primary"></span>
							</span>
						</div>
					</div>
					<div
					v-for="(sheet,sIndex) in workbook.sheets"
					v-bind:class="{hidden: isHidden(sIndex)}"
					>
					<div class="col-xs-3">
						<label for=""><span class="text-primary aliconfont icon-dot1"></span>主叫号码</label>
						<select class="form-control mt5" v-model='selectedColumns.from[sIndex]'>
							<option disabled value="">请选择</option>
							<option v-for='(header,hIndex) in sheet.headers' v-bind:value="hIndex">{{header}}</option>
						</select>
					</div>
					<div class="col-xs-3">
						<label for=""><span class="text-warning aliconfont icon-dot1"></span>被叫号码</label>
						<select class="form-control mt5" v-model='selectedColumns.to[sIndex]'>
							<option disabled value="">请选择</option>
							<option v-for='(header,hIndex) in sheet.headers' v-bind:value="hIndex">{{header}}</option>
						</select>
					</div>
					<div class="clearfix"></div>
				</div>
			</div>
		</form>
		<div v-if='workbook.hasInit' class="clearfix">
			<div
			v-for="(sheet,sIndex) in workbook.sheets"
			v-bind:class="{hidden: isHidden(sIndex)}"
			class="pull-right mt15">
			<span class="il-blk">
				<input class="labelauty-small" type="checkbox" v-model='includeHeaders[sIndex]' v-on:change='changeHeader(sIndex)' data-labelauty="包含表头"/>
			</span>
			<span class="il-blk">
				<input class="labelauty-small" type="radio" v-model='includeCheked[sIndex]' value='include' data-labelauty="包括已选行"/>
			</span>
			<span class="il-blk">
				<input  class="labelauty-small" type="radio" v-model='includeCheked[sIndex]' value='exclude' data-labelauty="排除已选行"/>
			</span>
		</div>
		<ul class="nav nav-tabs block-mt">
			<li
			v-for='(sn,snIndex) in workbook.sheetsNames'
			v-bind:class='{active: !isHidden(snIndex)}'
			v-on:click="switchSheet(snIndex)"
			><a>{{sn}}</a></li>
		</ul>
	</div>

	<table
	is='my-table'
	v-for='(sheet,sIndex) in workbook.sheets'
	v-bind:sheet='sheet'
	v-bind:selected-columns='selectedColumns'
	v-bind:sheet-index='sIndex'
	v-bind:checked-items='checkedItems'
	v-bind:check-all-status='checkAllStatus'
	v-bind:class='{hidden: isHidden(sIndex)}'
	v-bind:key='sheet.id'
	>
</table>
<!-- <ul class="pagination">
<li>
<a href="#">
<span>«</span>
</a>
</li>
<li class="active">
<a href="#">1</a>
</li>
<li>
<a href="#">2</a>
</li>
<li>
<a href="#">3</a>
</li>
<li>
<a href="#">4</a>
</li>
<li>
<a href="#">5</a>
</li>
<li>
<a href="#">
<span>»</span>
</a>
</li>
</ul> -->

<div v-if='workbook.hasInit' class="mt5">
	<form class="form-inline" style="display:inline">
		<input class="labelauty-small" type="checkbox" v-model="saveToDb" v-on:change="changeDataNoteStatus" data-labelauty="同时保存到数据库" />
		<input type="text" id="data-note" disabled="disabled" v-model="dataNote" class="form-control" placeholder="起个备注">
		<a class="btn btn-primary btn-long" v-on:click='submit' href="<%= tools_path(type: :calllist, sources: :excel) %>">确定</a>
		<a class="btn btn-default btn-long ml10" v-on:click='reload'>取消</a>
	</form>
</div>
</div>
</div>
</div>

app/views/tools/index.html.erb
<div id="calllist-analyse-index-app" data-diagram-id="<%= @diagram_id %>">
  <%= render "menus" %>
  <%= render "main" %>
  <%= render "sidebar" %>
</div>