config/routes.rb
Rails.application.routes.draw do

  resources :tactic_covers
  root 'dashboard#index'

  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }

  resources :calllists  do
    collection do
      get :export
      post :read_from_excel
      post :save_from_json
      get :load_note_options
      get :load_date_options
      get :load_batch_options
    end
  end

  resources :call_analyse_savers do
    collection do
      get :default
    end
  end

  resources :cases do
    collection do
      get :search
    end
  end

  resources :dashboard

  resources :extra_tasks do
    member do
      get :jump_to_execute
      get :jump_to_show
      get :jump_to_bind
    end
  end

  resources :image_views, only: [:index]

  resources :position_decisions

  resources :resources do
    collection do
      get :search
    end
  end

  resources :suspects

  resources :suspects_teams

  resources :tactics do
    member do
      get :get_tactic_tasks
      post :persist_tasks
      get :progress
      get :edit_covers
    end
  end

  resources :tactic_tasks

  resources :tools do
    collection do
      get :home
      get :add_info
      get :add_manual
      get :rlat
      get :rlat_details
    end
  end

  post 'users/search', to: 'users/users#search'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/call_analyse_saver.rb
class CallAnalyseSaver < ApplicationRecord
  belongs_to :user

  COLUMNS_ON_EXTRA_TASK = {
    id: "ID",
    title: "标题",
    created_at: "创建时间",
  }
  EXECUTE_PATH = "/tools/home"
  SEARCH_KEY = :title

end

app/models/calllist.rb
require 'roo'

class Calllist < ApplicationRecord

  #从文件读取数据,不作处理直接返回json
  def self.read(file)
    spread_sheets = Roo::Spreadsheet.open(file)
    sheets_names = spread_sheets.sheets
    sheets = sheets_names.map{|name| {:name=>name,:rows => spread_sheets.sheet(name).map{|rows| rows}}}
    #[{:name=>"name",:rows=>[[row]...],[],[]]
    return sheets
  end

end

app/models/case.rb
class Case < ApplicationRecord
  has_and_belongs_to_many :tactics
end

app/models/extra_task.rb
class ExtraTask < ApplicationRecord
  belongs_to :tactic_task

  TASK_MAP = {
    "话单分析": CallAnalyseSaver
  }
end

app/models/suspect.rb
class Suspect < ApplicationRecord
end

app/models/suspects_team.rb
class SuspectsTeam < ApplicationRecord
end

app/models/tactic.rb
class Tactic < ApplicationRecord
  has_and_belongs_to_many :cases
  accepts_nested_attributes_for :cases, allow_destroy: true
  has_many :tactic_tasks ,dependent:  :destroy
  has_and_belongs_to_many :tactic_covers

  def finished_task_count
    return self.tactic_tasks.where(:status => "已完成").size
  end

  def unfinished_task_count
    return self.tactic_tasks.where.not(:status => "已完成").size
  end

  def has_finish?
    return self.status == "已完成" && self.unfinished_task_count == 0
  end
end

app/models/tactic_category.rb
class TacticCategory < ApplicationRecord
end

app/models/tactic_cover.rb
class TacticCover < ApplicationRecord
  has_and_belongs_to_many :tactic
end

app/models/tactic_task.rb
class TacticTask < ApplicationRecord
  belongs_to :tactic
  has_and_belongs_to_many :user
  has_one :extra_task, dependent: :destroy

  after_create :create_extra_task

  LIST_OF_EXTRA_TASK = ["话单分析"]

  def should_do_extra_task
    return self.extra_task.present?
  end

  private
    def create_extra_task
      if LIST_OF_EXTRA_TASK.include?(self.category)
        self.create_extra_task!(:name => self.category)
      end
    end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, #:registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_and_belongs_to_many :tactic_task
end

app/controllers/suspects_teams_controller.rb
class SuspectsTeamsController < ApplicationController
  before_action :set_suspects_team, only: [:show, :edit, :update, :destroy]

  # GET /suspects_teams
  # GET /suspects_teams.json
  def index
    #@suspects_teams = SuspectsTeam.all
  end

  # GET /suspects_teams/1
  # GET /suspects_teams/1.json
  def show
      @suspects_teams = SuspectsTeam.all

      #@curr_suspects_teams_id = @suspects_team.id
  end

  # GET /suspects_teams/new
  def new
    @suspects_team = SuspectsTeam.new
  end

  # GET /suspects_teams/1/edit
  def edit
  end

  # POST /suspects_teams
  # POST /suspects_teams.json
  def create
    @suspects_team = SuspectsTeam.new(suspects_team_params)

    respond_to do |format|
      if @suspects_team.save
        format.html { redirect_to @suspects_team, notice: 'Suspects team was successfully created.' }
        format.json { render :show, status: :created, location: @suspects_team }
      else
        format.html { render :new }
        format.json { render json: @suspects_team.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /suspects_teams/1
  # PATCH/PUT /suspects_teams/1.json
  def update
    respond_to do |format|
      if @suspects_team.update(suspects_team_params)
        format.html { redirect_to @suspects_team, notice: 'Suspects team was successfully updated.' }
        format.json { render :show, status: :ok, location: @suspects_team }
      else
        format.html { render :edit }
        format.json { render json: @suspects_team.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /suspects_teams/1
  # DELETE /suspects_teams/1.json
  def destroy
    @suspects_team.destroy
    respond_to do |format|
      format.html { redirect_to suspects_teams_url, notice: 'Suspects team was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_suspects_team
      @suspects_team = SuspectsTeam.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def suspects_team_params
      params.require(:suspects_team).permit(:name, :catalog, :company, :addr, :account, :photo)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/calllists_helper.rb
module CalllistsHelper
end

app/helpers/cases_helper.rb
module CasesHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/excel_helper.rb
module ExcelHelper
end

app/helpers/resources_helper.rb
module ResourcesHelper
end

app/helpers/suspects_helper.rb
module SuspectsHelper
end

app/helpers/suspects_teams_helper.rb
module SuspectsTeamsHelper
end

app/helpers/tactics_helper.rb
module TacticsHelper
end

app/helpers/tools_helper.rb
module ToolsHelper
end

app/views/suspects_teams/_form.html.erb
<%= form_with(model: suspects_team, local: true) do |form| %>
  <% if suspects_team.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(suspects_team.errors.count, "error") %> prohibited this suspects_team from being saved:</h2>

      <ul>
      <% suspects_team.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :suspects_team_name %>
  </div>

  <div class="field">
    <%= form.label :catalog %>
    <%= form.text_field :catalog, id: :suspects_team_catalog %>
  </div>

  <div class="field">
    <%= form.label :company %>
    <%= form.text_field :company, id: :suspects_team_company %>
  </div>

  <div class="field">
    <%= form.label :addr %>
    <%= form.text_field :addr, id: :suspects_team_addr %>
  </div>

  <div class="field">
    <%= form.label :account %>
    <%= form.text_field :account, id: :suspects_team_account %>
  </div>

  <div class="field">
    <%= form.label :photo %>
    <%= form.text_field :photo, id: :suspects_team_photo %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/suspects_teams/edit.html.erb
<h1>Editing Suspects Team</h1>

<%= render 'form', suspects_team: @suspects_team %>

<%= link_to 'Show', @suspects_team %> |
<%= link_to 'Back', suspects_teams_path %>

app/views/suspects_teams/index.html.erb
<div class="analysis-wrap">
<div class="bread-nav-wrap">
    <ul class="bread-nav clearfix">
      <li class="bread-nav-item home">
        <a class="link-item" href=""><span class="glyphicon glyphicon-home"></span></a>
      </li>
      <li class="bread-nav-item">
        <span class="link-item" href="">嫌疑犯团伙详情</span>
      </li>
    </ul>
  </div>
  <!-- 路径导航 end -->
  <div class="left-side left-side-inverse column-18">
    <div class="left-side-heading">
      <div class="heading-title">
        <a class="pull-right small" href="">回首页</a>
        嫌疑犯
      </div>
      <div class="input-group">
        <input type="text" class="form-control" value="搜索">
        <span class="input-group-btn">
          <button class="btn btn-primary" type="button">
          搜
          </button>
        </span>
      </div>
    </div>
    <ul class="analysis-img-list">
      <li class="list-item active">
        <a href="#" class="img-wrap">
          <%= image_tag("rectangle1.png")%>
          <div class="img-title">Midred Ortega</div>
        </a>
      </li>
      <li class="list-item">
        <a href="#" class="img-wrap">
          <%= image_tag("rectangle2.png")%>
          <div class="img-title">Midred Ortega</div>
        </a>
      </li>
      <li class="list-item">
        <a href="#" class="img-wrap">
          <%= image_tag("rectangle4.png")%>
          <div class="img-title">Midred Ortega</div>
        </a>
      </li>
      <li class="list-item">
        <a href="#" class="img-wrap">
          <%= image_tag("rectangle7.png")%>
          <div class="img-title">Midred Ortega</div>
        </a>
      </li>
    </ul>
  </div>
  <!-- left-side end -->
  <div class="right-side column-24">
    <div class="inner-panel">
      <div class="panel-heading">
        <div class="panel-title">
          团伙成员
        </div>
      </div>
      <div class="block-plr">
        <ul class="media-list media-img40">
          <li class="media">
            <div class="media-left">
              <%= image_tag("people1.png",:class => "img-circle")%>
            </div>
            <div class="media-body">
              <div class="media-heading">Nicole Harrison</div>
              <div class="text-muted">母亲，82岁，女</div>
            </div>
          </li>
          <li class="media">
            <div class="media-left">
              <%= image_tag("people2.png",:class => "img-circle")%>
            </div>
            <div class="media-body">
              <div class="media-heading">Nicole Harrison</div>
              <div class="text-muted">母亲，82岁，女</div>
            </div>
          </li>
          <li class="media">
            <div class="media-left">
              <%= image_tag("people3.png",:class => "img-circle")%>
            </div>
            <div class="media-body">
              <div class="media-heading">Nicole Harrison</div>
              <div class="text-muted">母亲，82岁，女</div>
            </div>
          </li>
          <li class="media">
            <div class="media-left">
              <%= image_tag("people1.png",:class => "img-circle")%>
            </div>
            <div class="media-body">
              <div class="media-heading">Nicole Harrison</div>
              <div class="text-muted">母亲，82岁，女</div>
            </div>
          </li>
          <li class="media">
            <div class="media-left">
              <%= image_tag("people4.png",:class => "img-circle")%>
            </div>
            <div class="media-body">
              <div class="media-heading">Nicole Harrison</div>
              <div class="text-muted">母亲，82岁，女</div>
            </div>
          </li>
        </ul>
      </div>
    </div>
    <div class="inner-panel">
      <div class="panel-heading">
        <div class="panel-title">
          关联车辆
        </div>
      </div>
      <div class="block-plr">
        <ul class="media-list media-img40">
          <li class="media">
            <div class="media-left">
             <%= image_tag("car_def.png",:class => "img-circle")%>
            </div>
            <div class="media-body">
              <div class="media-heading">5-214-34-038</div>
              <div class="text-muted">白色，轿车</div>
            </div>
          </li>
          <li class="media">
            <div class="media-left">
              <%= image_tag("car_def.png",:class => "img-circle")%>
            </div>
            <div class="media-body">
              <div class="media-heading">5-214-34-038</div>
              <div class="text-muted">白色，轿车</div>
            </div>
          </li>
          <li class="media">
            <div class="media-left">
             <%= image_tag("car_def.png",:class => "img-circle")%>
            </div>
            <div class="media-body">
              <div class="media-heading">5-214-34-038</div>
              <div class="text-muted">白色，轿车</div>
            </div>
          </li>
          <li class="media">
            <div class="media-left">
              <%= image_tag("car_def.png",:class => "img-circle")%>
            </div>
            <div class="media-body">
              <div class="media-heading">5-214-34-038</div>
              <div class="text-muted">白色，轿车</div>
            </div>
          </li>
        </ul>
      </div>
    </div>
    <div class="inner-panel">
      <div class="panel-heading">
        <div class="panel-title">
          关联文档
        </div>
      </div>
      <div class="block-plr">
        <ul class="media-list media-img40">
          <li class="media">
            <div class="media-left">
              <%= image_tag("documemt_def.png",:class => "img-circle")%>
            </div>
            <div class="media-body">
              <div class="media-heading">嫌疑团伙调查资料</div>
              <div class="text-gray">重要，1月2日 20:34</div>
            </div>
          </li>
          <li class="media">
            <div class="media-left">
              <%= image_tag("img_def.png",:class => "img-circle")%>
            </div>
            <div class="media-body">
              <div class="media-heading">车辆图片-大众cc,车辆</div>
              <div class="text-gray">重要，1月2日 20:34</div>
            </div>
          </li>
          <li class="media">
            <div class="media-left">
              <%= image_tag("excel_def.png",:class => "img-circle")%>
            </div>
            <div class="media-body">
              <div class="media-heading">团伙成员手机通讯录</div>
              <div class="text-gray">重要，1月2日 20:34</div>
            </div>
          </li>
          <li class="media">
            <div class="media-left">
               <%= image_tag("audio_def.png",:class => "img-circle")%>
            </div>
            <div class="media-body">
              <div class="media-heading">团伙成员审讯录音</div>
              <div class="text-gray">重要，1月2日 20:34</div>
            </div>
          </li>
        </ul>
      </div>
    </div>
  </div>
  <!-- right-side end -->
  <div class="container-18-24">
    <div class="panel panel-default">
      <div class="panel-body">
        <div class="info-show">
          <div class="info-left">
            <%= image_tag("people1.png")%>
          </div>
          <div class="info-body">
            <div class="info-heading clearfix">
              <div class="pull-left">
                <span class="info-name">张三团伙</span>
                <div class="mt5">
                  <span class="label label-warning mr10">走私</span>
                  <span class="label label-warning mr10">代销</span>
                  <span class="label label-warning mr10">黑社会</span>
                </div>
              </div>
              <div class="ico-tool-list pull-right">
                <a class="ico-wrap" href="">
                  <div class="ico-name">5人</div>
                  <div class="text-gray">
                    <span class="aliconfont icon-family f14"></span> 团伙成员
                  </div>
                </a>
                <a class="ico-wrap" href="">
                  <div class="ico-name">5件</div>
                  <div class="text-gray">
                    <span class="aliconfont icon-file f14"></span> 关联案件
                  </div>
                </a>
                <a class="ico-wrap" href="">
                  <div class="ico-name">5人</div>
                  <div class="text-gray">
                    <span class="aliconfont icon-car f14"></span> 关联车辆
                  </div>
                </a>
                <a class="ico-wrap" href="">
                  <div class="ico-name">5台</div>
                  <div class="text-gray">
                    <span class="glyphicon glyphicon-file f14"></span> 关联文档
                  </div>
                </a>
                <a class="ico-wrap" href="">
                  <div class="ico-name">5份</div>
                  <div class="text-gray">
                    <span class="aliconfont icon-tab f14"></span> 标签信息
                  </div>
                </a>
              </div>
            </div>
            <div class="info-list-wrap">
              <ul class="float-ul wu2 clearfix lh22">
                <li class="float-ul-item">名称：张三团伙</li>
                <li class="float-ul-item">公司：山东市东花贸易运输有限责任公司</li>
                <li class="float-ul-item">团队类型：走私</li>
                <li class="float-ul-item">注册地址：山东市东花北里20号楼01单元701室</li>
                <li class="float-ul-item">团伙成员：10人</li>
                <li class="float-ul-item">公司账户：230583085</li>
                <li class="float-ul-item">1号人物：张三</li>
                <li class="float-ul-item">&nbsp;</li>
                <li class="float-ul-item">2号人物：李四</li>
                <li class="float-ul-item">&nbsp;</li>
                <li class="float-ul-item">3号人物：王五</li>
                <li class="float-ul-item">&nbsp;</li>
              </ul>
            </div>
          </div>
        </div>
      </div>
      <hr>
      <div class="inner-panel-heading">
        <div class="panel-title">
          <div class="pull-right">
            <ul class="nav-line-space list-unstyled">
              <li class="active"><a href="">人际关系分析</a></li>
              <li><a href="">出行轨迹分析</a></li>
              <li><a href="">资金流转分析</a></li>
              <li><a href="">物流往来分析</a></li>
            </ul>
          </div>
          关联案件
        </div>
      </div>
      <div class="panel-body">
        <ul class="media-list media-time-axis">
          <li class="media">
            <div class="media-left">
              <%= image_tag("rectangle-a1.png",:class => "media-object")%>
            </div>
            <div class="media-body">
              <div class="title-conponent">
                <small class="pull-right text-gray">
                  <span class="glyphicon glyphicon-calendar text-primary"></span>&nbsp;2017-12-12&nbsp;12:12:12
                </small>
                <span class="f16">117走私案</span>
                <span class="label label-danger ml10">未结案</span>
              </div>
              <div class="text-muted">
              黄埔海关5月24日对外通报，该关成功捣毁了５个涉嫌走私进口光电材料的犯罪团伙。截至24日9点，抓获犯罪嫌疑人78名，现场查扣涉嫌走私进口的光电材料一批。经查，2014年以来，涉案走私团伙共走私进口光电材料约6300吨，案值约10亿元。５月２４日凌晨5：30分，专案指挥部统一下达抓捕命令，近千名警力分成143个行动小组，分别在广州、深圳、东莞、中山、江门、武汉、成都、长沙、玉林等地同步开展收网行动，成功捣毁了上述犯罪团伙，一举抓获78名犯罪嫌疑人。
              </div>
            </div>
          </li>
          <li class="media">
            <div class="media-left">
              <%= image_tag("rectangle-a1.png",:class => "media-object")%>
            </div>
            <div class="media-body">
              <div class="title-conponent">
                <small class="pull-right text-gray">
                  <span class="glyphicon glyphicon-calendar text-primary"></span>&nbsp;2017-12-12&nbsp;12:12:12
                </small>
                <span class="f16">117走私案</span>
                <span class="label label-success ml10">已结案</span>
              </div>
              <div class="text-muted">
              黄埔海关5月24日对外通报，该关成功捣毁了５个涉嫌走私进口光电材料的犯罪团伙。截至24日9点，抓获犯罪嫌疑人78名，现场查扣涉嫌走私进口的光电材料一批。经查，2014年以来，涉案走私团伙共走私进口光电材料约6300吨，案值约10亿元。５月２４日凌晨5：30分，专案指挥部统一下达抓捕命令，近千名警力分成143个行动小组，分别在广州、深圳、东莞、中山、江门、武汉、成都、长沙、玉林等地同步开展收网行动，成功捣毁了上述犯罪团伙，一举抓获78名犯罪嫌疑人。
              </div>
            </div>
          </li>
          <li class="media">
            <div class="media-left">
              <%= image_tag("rectangle-a1.png",:class => "media-object")%>
            </div>
            <div class="media-body">
              <div class="title-conponent">
                <small class="pull-right text-gray">
                  <span class="glyphicon glyphicon-calendar text-primary"></span>&nbsp;2017-12-12&nbsp;12:12:12
                </small>
                <span class="f16">117走私案</span>
                <span class="label label-success ml10">已结案</span>
              </div>
              <div class="text-muted">
              黄埔海关5月24日对外通报，该关成功捣毁了５个涉嫌走私进口光电材料的犯罪团伙。截至24日9点，抓获犯罪嫌疑人78名，现场查扣涉嫌走私进口的光电材料一批。经查，2014年以来，涉案走私团伙共走私进口光电材料约6300吨，案值约10亿元。５月２４日凌晨5：30分，专案指挥部统一下达抓捕命令，近千名警力分成143个行动小组，分别在广州、深圳、东莞、中山、江门、武汉、成都、长沙、玉林等地同步开展收网行动，成功捣毁了上述犯罪团伙，一举抓获78名犯罪嫌疑人。
              </div>
            </div>
          </li>
        </ul>
      </div>
    </div>
  </div>
  </div>

app/views/suspects_teams/new.html.erb
<h1>New Suspects Team</h1>

<%= render 'form', suspects_team: @suspects_team %>

<%= link_to 'Back', suspects_teams_path %>