config/routes.rb
Rails.application.routes.draw do

  resources :tactic_covers
  root 'dashboard#index'

  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }

  resources :calllists  do
    collection do
      get :export
      post :read_from_excel
      post :save_from_json
      get :load_note_options
      get :load_date_options
      get :load_batch_options
    end
  end

  resources :call_analyse_savers do
    collection do
      get :default
    end
  end

  resources :cases do
    collection do
      get :search
    end
  end

  resources :dashboard

  resources :extra_tasks do
    member do
      get :jump_to_execute
      get :jump_to_show
      get :jump_to_bind
    end
  end

  resources :image_views, only: [:index]

  resources :position_decisions

  resources :resources do
    collection do
      get :search
    end
  end

  resources :suspects

  resources :suspects_teams

  resources :tactics do
    member do
      get :get_tactic_tasks
      post :persist_tasks
      get :progress
      get :edit_covers
    end
  end

  resources :tactic_tasks

  resources :tools do
    collection do
      get :home
      get :add_info
      get :add_manual
      get :rlat
      get :rlat_details
    end
  end

  post 'users/search', to: 'users/users#search'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/call_analyse_saver.rb
class CallAnalyseSaver < ApplicationRecord
  belongs_to :user

  COLUMNS_ON_EXTRA_TASK = {
    id: "ID",
    title: "标题",
    created_at: "创建时间",
  }
  EXECUTE_PATH = "/tools/home"
  SEARCH_KEY = :title

end

app/models/calllist.rb
require 'roo'

class Calllist < ApplicationRecord

  #从文件读取数据,不作处理直接返回json
  def self.read(file)
    spread_sheets = Roo::Spreadsheet.open(file)
    sheets_names = spread_sheets.sheets
    sheets = sheets_names.map{|name| {:name=>name,:rows => spread_sheets.sheet(name).map{|rows| rows}}}
    #[{:name=>"name",:rows=>[[row]...],[],[]]
    return sheets
  end

end

app/models/case.rb
class Case < ApplicationRecord
  has_and_belongs_to_many :tactics
end

app/models/extra_task.rb
class ExtraTask < ApplicationRecord
  belongs_to :tactic_task

  TASK_MAP = {
    "话单分析": CallAnalyseSaver
  }
end

app/models/suspect.rb
class Suspect < ApplicationRecord
end

app/models/suspects_team.rb
class SuspectsTeam < ApplicationRecord
end

app/models/tactic.rb
class Tactic < ApplicationRecord
  has_and_belongs_to_many :cases
  accepts_nested_attributes_for :cases, allow_destroy: true
  has_many :tactic_tasks ,dependent:  :destroy
  has_and_belongs_to_many :tactic_covers

  def finished_task_count
    return self.tactic_tasks.where(:status => "已完成").size
  end

  def unfinished_task_count
    return self.tactic_tasks.where.not(:status => "已完成").size
  end

  def has_finish?
    return self.status == "已完成" && self.unfinished_task_count == 0
  end
end

app/models/tactic_category.rb
class TacticCategory < ApplicationRecord
end

app/models/tactic_cover.rb
class TacticCover < ApplicationRecord
  has_and_belongs_to_many :tactic
end

app/models/tactic_task.rb
class TacticTask < ApplicationRecord
  belongs_to :tactic
  has_and_belongs_to_many :user
  has_one :extra_task, dependent: :destroy

  after_create :create_extra_task

  LIST_OF_EXTRA_TASK = ["话单分析"]

  def should_do_extra_task
    return self.extra_task.present?
  end

  private
    def create_extra_task
      if LIST_OF_EXTRA_TASK.include?(self.category)
        self.create_extra_task!(:name => self.category)
      end
    end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, #:registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_and_belongs_to_many :tactic_task
end

app/helpers/calllists_helper.rb
module CalllistsHelper
end

app/helpers/cases_helper.rb
module CasesHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/excel_helper.rb
module ExcelHelper
end

app/helpers/resources_helper.rb
module ResourcesHelper
end

app/helpers/suspects_helper.rb
module SuspectsHelper
end

app/helpers/tactics_helper.rb
module TacticsHelper
end

app/helpers/tools_helper.rb
module ToolsHelper
end

app/views/resources/_bread_nav.html.erb
<div class="bread-nav-wrap">
    <ul class="bread-nav clearfix">
      <li class="bread-nav-item home">
        <a class="link-item" class="link-item" href="<%= root_path %>"><span class="glyphicon glyphicon-home"></span></a>
      </li>
      <li class="bread-nav-item">
        <a class="link-item" href="">综合搜索</a>
      </li>
      <li class="bread-nav-item">
        <span class="link-item">
          <% case @search_type 
              when "infomation" %>
                  情报资料
          <% when "doc" %>
                  文档库
          <% when "image" %>
                  图片库
          <% when "video" %>
                  视频库
          <% else 
             end %>
        </span>
      </li>
    </ul>
  </div>

app/views/resources/_comp_search_form.html.erb
<!-- 综合搜索表单  -->
<%= form_tag("/resources/search", method: "get",class: "input-group") do %>
	<%= hidden_field_tag 'type', @search_type %>
  	<%= text_field_tag("key","",class: "form-control",:placeholder => '搜索',
  	 					value:@search_text) %>
	<span class="input-group-btn">
		<button class="btn btn-primary" type="submit">
			<span class="glyphicon glyphicon-search"></span>
		</button>
    </span>
<% end %>


app/views/resources/_form.html.erb
<%= form_with(model: resource, local: true) do |form| %>
  <% if resource.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(resource.errors.count, "error") %> prohibited this resource from being saved:</h2>

      <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/resources/_leftside.html.erb
 <div class="left-side left-side-inverse column-18">
    <div class="left-side-heading">
      <div class="heading-title">
        <a class="pull-right small" href="<%= root_path %>">回首页</a>
        分类
      </div>
<!--       <div class="input-group">
        <input type="text" class="form-control" value="搜索">
        <span class="input-group-btn">
          <button class="btn btn-primary" type="button">
            <span class="glyphicon glyphicon-search"></span>
          </button>
        </span>
      </div> -->
   <%= render 'comp_search_form', resource: @resource %>
    </div>
    <div class="left-side-btn-menu">
      <a href="<%= "#{search_resources_path}?type=infomation" %>" class="btn btn-normal btn-block <% if @search_type == 'infomation' %>active<% end %>" type="button">情报资料库</a>
      <a href="<%= "#{search_resources_path}?type=doc" %>" class="btn btn-normal btn-block <% if @search_type == 'doc' %>active<% end %>" type="button">文档库</a>
      <a href="<%= "#{search_resources_path}?type=image" %>" class="btn btn-normal btn-block <% if @search_type == 'image' %>active<% end %>" type="button">图片库</a>
      <a href="<%= "#{search_resources_path}?type=video" %>" class="btn btn-normal btn-block <% if @search_type == 'video' %>active<% end %>" type="button">视频库</a>
    </div>
  </div>
  <!-- left-side end -->

app/views/resources/_rightside_doc.html.erb
<div class="container-18">
		<div class="panel panel-default">
			<div class="row">
				<div class="col-md-8 col-sm-7">
					<div class="inner-panel-heading">
						<span class="ml10">文档类型：</span>
						<label class="radio-ui">
							<i class="ico-radio selected"><input type="radio"></i>
							全部
						</label>
						<label class="radio-ui">
							<i class="ico-radio"><input type="radio"></i>
							DOC
						</label>
						<label class="radio-ui">
							<i class="ico-radio"><input type="radio"></i>
							XLS
						</label>
						<label class="radio-ui">
							<i class="ico-radio"><input type="radio"></i>
							TXT
						</label>
					</div>
					<hr>
					<div class="panel-body">
						<ul class="media-list">
							<li class="media media-img40">
								<div class="media-left">
									<%= image_tag("audio_def.png")%>
								</div>
								<div class="media-body">
									<div class="media-heading">
										<a class="text-gray-dark" href="">
											<u>
											<span class="text-danger">情报分析</span>相关工具与功能整理
											</u>
										</a>
									</div>
									<div>
										<span class="text-danger">情报分析</span>
										相关工具与功能整理一. 现有工具类整理介绍包括开源免费的软件和商业软件(有功能限制的免费版、可内部使用的破解版) 。这些
									</div>
									<div class="clearfix text-gray mt5">
										<button class="btn btn-primary pull-right btn-sm btn-long" type="button">下载</button>
										<div class="mt10">
											2015-01-31
											<span class="line-space">|</span>
											共6页
											<span class="line-space">|</span>
											29次下载
											<span class="line-space">|</span>
											作者：松夫子
										</div>
									</div>
								</div>
							</li>
							<li class="media media-img40">
								<div class="media-left">
									<%= image_tag("documemt_def.png")%>
								</div>
								<div class="media-body">
									<div class="media-heading">
										<a class="text-gray-dark" href="">
											<u>
											<span class="text-danger">情报分析</span>相关工具与功能整理
											</u>
										</a>
									</div>
									<div>
										<span class="text-danger">情报分析</span>
										相关工具与功能整理一. 现有工具类整理介绍包括开源免费的软件和商业软件(有功能限制的免费版、可内部使用的破解版) 。这些
									</div>
									<div class="clearfix text-gray mt5">
										<button class="btn btn-primary pull-right btn-sm btn-long" type="button">下载</button>
										<div class="mt10">
											2015-01-31
											<span class="line-space">|</span>
											共6页
											<span class="line-space">|</span>
											29次下载
											<span class="line-space">|</span>
											作者：松夫子
										</div>
									</div>
								</div>
							</li>
							<li class="media media-img40">
								<div class="media-left">
									<%= image_tag("excel_def.png")%>
								</div>
								<div class="media-body">
									<div class="media-heading">
										<a class="text-gray-dark" href="">
											<u>
											<span class="text-danger">情报分析</span>相关工具与功能整理
											</u>
										</a>
									</div>
									<div>
										<span class="text-danger">情报分析</span>
										相关工具与功能整理一. 现有工具类整理介绍包括开源免费的软件和商业软件(有功能限制的免费版、可内部使用的破解版) 。这些
									</div>
									<div class="clearfix text-gray mt5">
										<button class="btn btn-primary pull-right btn-sm btn-long" type="button">下载</button>
										<div class="mt10">
											2015-01-31
											<span class="line-space">|</span>
											共6页
											<span class="line-space">|</span>
											29次下载
											<span class="line-space">|</span>
											作者：松夫子
										</div>
									</div>
								</div>
							</li>
							<li class="media media-img40">
								<div class="media-left">
									<%= image_tag("img_def.png")%>
								</div>
								<div class="media-body">
									<div class="media-heading">
										<a class="text-gray-dark" href="">
											<u>
											<span class="text-danger">情报分析</span>相关工具与功能整理
											</u>
										</a>
									</div>
									<div>
										<span class="text-danger">情报分析</span>
										相关工具与功能整理一. 现有工具类整理介绍包括开源免费的软件和商业软件(有功能限制的免费版、可内部使用的破解版) 。这些
									</div>
									<div class="clearfix text-gray mt5">
										<button class="btn btn-primary pull-right btn-sm btn-long" type="button">下载</button>
										<div class="mt10">
											2015-01-31
											<span class="line-space">|</span>
											共6页
											<span class="line-space">|</span>
											29次下载
											<span class="line-space">|</span>
											作者：松夫子
										</div>
									</div>
								</div>
							</li>
							<li class="media media-img40">
								<div class="media-left">
									<%= image_tag("img_def.png")%>
								</div>
								<div class="media-body">
									<div class="media-heading">
										<a class="text-gray-dark" href="">
											<u>
											<span class="text-danger">情报分析</span>相关工具与功能整理
											</u>
										</a>
									</div>
									<div>
										<span class="text-danger">情报分析</span>
										相关工具与功能整理一. 现有工具类整理介绍包括开源免费的软件和商业软件(有功能限制的免费版、可内部使用的破解版) 。这些
									</div>
									<div class="clearfix text-gray mt5">
										<button class="btn btn-primary pull-right btn-sm btn-long" type="button">下载</button>
										<div class="mt10">
											2015-01-31
											<span class="line-space">|</span>
											共6页
											<span class="line-space">|</span>
											29次下载
											<span class="line-space">|</span>
											作者：松夫子
										</div>
									</div>
								</div>
							</li>
						</ul>
						<ul class="pagination">
							<li>
								<a href="#">
									<span>&laquo;</span>
								</a>
							</li>
							<li class="active">
								<a href="#">1</a>
							</li>
							<li>
								<a href="#">2</a>
							</li>
							<li>
								<a href="#">3</a>
							</li>
							<li>
								<a href="#">4</a>
							</li>
							<li>
								<a href="#">5</a>
							</li>
							<li>
								<a href="#">
									<span>&raquo;</span>
								</a>
							</li>
						</ul>
					</div>
				</div>
				<div class="col-md-4 col-sm-5">
					<div class="search-wrap">
						<div class="alert alert-success">
							<span class="close" data-dismiss='alert'>&times;</span>
							智能搜索为你找到相关结果100个
						</div>
						<div class="block-mb">
							<span class="glyphicon glyphicon-filter text-gray"></span>
							<span class="inner-panel-subtitle">搜索条件</span>
						</div>
						<ul class="list-unstyled search-condition">
							<li>
								<dl class="condition-group">
									<dt class="condition-field">页数：</dt>
									<dd class="condition-item-group">
									  	<a class="condition-item text-primary" href="">全部</a>
									  	<a class="condition-item text-gray-dark" href="">0-5页</a>
									  	<a class="condition-item text-gray-dark" href="">6-10页</a>
									  	<a class="condition-item text-gray-dark" href="">10页以上</a>
									</dd>
								</dl>
								<dl class="condition-group">
									<dt class="condition-field">发布时间：</dt>
									    <dd class="condition-item-group">
									  	    <a class="condition-item" href="">全部</a>
									  	    <a class="condition-item text-gray-dark" href="">1个月内</a>
									  	    <a class="condition-item text-gray-dark" href="">6个月内</a>
									    </dd>
								</dl>
								<dl class="condition-group">
									<dt class="condition-field">排序：</dt>
									<dd class="condition-item-group">
									  	<a class="condition-item" href="">最近上传</a>
									  	<a class="condition-item text-gray-dark" href="">最多下载</a>
									</dd>
								</dl>
							</li>
						</ul>
					</div>
				</div>
			</div>
		</div>
	</div>

app/views/resources/_rightside_img.html.erb
<div class="left-side-btn-menu">
			<a href="" class="btn btn-normal btn-block" type="button">情报资料库</a>	
			<a href="" class="btn btn-normal btn-block" type="button">文档库</a>	
			<a href="" class="btn btn-normal btn-block active" type="button">图片库</a>	
			<a href="" class="btn btn-normal btn-block" type="button">视频库</a>	
		</div>

app/views/resources/_rightside_video.html.erb
<div class="container-18">
		<div class="panel panel-default">
			<div class="row">
				<div class="col-md-8 col-sm-7">
					<div class="panel-body">
						<div class="img-column">
							<ul class="clearfix list-unstyled block-list">
								<li class="col-xs-6 col-md-4 col-lg-3">
									<a class="img-wrap img-adapt" href="#">
										<div class="z-cell">
											<%= image_tag("vedio.png")%>
										</div>
										<div class="img-title">
											<span class="pull-right">1:00:20</span>
											白云机场
										</div>
									</a>
									<div class="text-ellipsis mt5">
										<a class="text-muted" href="">广州：海关查获外籍<span class="text-danger">走私毒品</span>,共133吨</a>
									</div>
								</li>
								<li class="col-xs-6 col-md-4 col-lg-3">
									<a class="img-wrap img-adapt" href="#">
										<div class="z-cell">
											<%= image_tag("vedio.png")%>
										</div>
										<div class="img-title">
											<span class="pull-right">1:00:20</span>
											白云机场
										</div>
									</a>
									<div class="text-ellipsis mt5">
										<a class="text-muted" href="">广州：海关查获外籍<span class="text-danger">走私毒品</span></a>
									</div>
								</li>
								<li class="col-xs-6 col-md-4 col-lg-3">
									<a class="img-wrap img-adapt" href="#">
										<div class="z-cell">
											<%= image_tag("vedio.png")%>
										</div>
										<div class="img-title">
											<span class="pull-right">1:00:20</span>
											白云机场
										</div>
									</a>
									<div class="text-ellipsis mt5">
										<a class="text-muted" href="">广州：海关查获外籍<span class="text-danger">走私毒品</span></a>
									</div>
								</li>
								<li class="col-xs-6 col-md-4 col-lg-3">
									<a class="img-wrap img-adapt" href="#">
										<div class="z-cell">
											<%= image_tag("vedio.png")%>
										</div>
										<div class="img-title">
											<span class="pull-right">1:00:20</span>
											白云机场
										</div>
									</a>
									<div class="text-ellipsis mt5">
										<a class="text-muted" href="">广州：海关查获外籍<span class="text-danger">走私毒品</span></a>
									</div>
								</li>
								<li class="col-xs-6 col-md-4 col-lg-3">
									<a class="img-wrap img-adapt" href="#">
										<div class="z-cell">
											<%= image_tag("vedio.png")%>
										</div>
										<div class="img-title">
											<span class="pull-right">1:00:20</span>
											白云机场
										</div>
									</a>
									<div class="text-ellipsis mt5">
										<a class="text-muted" href="">广州：海关查获外籍<span class="text-danger">走私毒品</span></a>
									</div>
								</li>
								<li class="col-xs-6 col-md-4 col-lg-3">
									<a class="img-wrap img-adapt" href="#">
										<div class="z-cell">
											<%= image_tag("vedio.png")%>
										</div>
										<div class="img-title">
											<span class="pull-right">1:00:20</span>
											白云机场
										</div>
									</a>
									<div class="text-ellipsis mt5">
										<a class="text-muted" href="">广州：海关查获外籍<span class="text-danger">走私毒品</span></a>
									</div>
								</li>
								<li class="col-xs-6 col-md-4 col-lg-3">
									<a class="img-wrap img-adapt" href="#">
										<div class="z-cell">
											<%= image_tag("vedio.png")%>
										</div>
										<div class="img-title">
											<span class="pull-right">1:00:20</span>
											白云机场
										</div>
									</a>
									<div class="text-ellipsis mt5">
										<a class="text-muted" href="">广州：海关查获外籍<span class="text-danger">走私毒品</span></a>
									</div>
								</li>
								<li class="col-xs-6 col-md-4 col-lg-3">
									<a class="img-wrap img-adapt" href="#">
										<div class="z-cell">
											<%= image_tag("vedio.png")%>
										</div>
										<div class="img-title">
											<span class="pull-right">1:00:20</span>
											白云机场
										</div>
									</a>
									<div class="text-ellipsis mt5">
										<a class="text-muted" href="">广州：海关查获外籍<span class="text-danger">走私毒品</span></a>
									</div>
								</li>
								<li class="col-xs-6 col-md-4 col-lg-3">
									<a class="img-wrap img-adapt" href="#">
										<div class="z-cell">
											<%= image_tag("vedio.png")%>
										</div>
										<div class="img-title">
											<span class="pull-right">1:00:20</span>
											白云机场
										</div>
									</a>
									<div class="text-ellipsis mt5">
										<a class="text-muted" href="">广州：海关查获外籍<span class="text-danger">走私毒品</span></a>
									</div>
								</li>
								<li class="col-xs-6 col-md-4 col-lg-3">
									<a class="img-wrap img-adapt" href="#">
										<div class="z-cell">
											<%= image_tag("vedio.png")%>
										</div>
										<div class="img-title">
											<span class="pull-right">1:00:20</span>
											白云机场
										</div>
									</a>
									<div class="text-ellipsis mt5">
										<a class="text-muted" href="">广州：海关查获外籍<span class="text-danger">走私毒品</span></a>
									</div>
								</li>
								<li class="col-xs-6 col-md-4 col-lg-3">
									<a class="img-wrap img-adapt" href="#">
										<div class="z-cell">
											<%= image_tag("vedio.png")%>
										</div>
										<div class="img-title">
											<span class="pull-right">1:00:20</span>
											白云机场
										</div>
									</a>
									<div class="text-ellipsis mt5">
										<a class="text-muted" href="">广州：海关查获外籍<span class="text-danger">走私毒品</span></a>
									</div>
								</li>
								<li class="col-xs-6 col-md-4 col-lg-3">
									<a class="img-wrap img-adapt" href="#">
										<div class="z-cell">
											<%= image_tag("vedio.png")%>
										</div>
										<div class="img-title">
											<span class="pull-right">1:00:20</span>
											白云机场
										</div>
									</a>
									<div class="text-ellipsis mt5">
										<a class="text-muted" href="">广州：海关查获外籍<span class="text-danger">走私毒品</span></a>
									</div>
								</li>
							</ul>
						</div>
						<ul class="pagination">
							<li>
								<a href="#">
									<span>&laquo;</span>
								</a>
							</li>
							<li class="active">
								<a href="#">1</a>
							</li>
							<li>
								<a href="#">2</a>
							</li>
							<li>
								<a href="#">3</a>
							</li>
							<li>
								<a href="#">4</a>
							</li>
							<li>
								<a href="#">5</a>
							</li>
							<li>
								<a href="#">
									<span>&raquo;</span>
								</a>
							</li>
						</ul>
						<!-- paginatin end -->
					</div>


				</div>
				<div class="col-md-4 col-sm-5">
					<div class="search-wrap">
						<div class="alert alert-success">
							<span class="close" data-dismiss='alert'>&times;</span>
							智能搜索为你找到相关结果100个
						</div>
						<div class="block-mb">
							<span class="glyphicon glyphicon-filter text-gray"></span>
							<span class="inner-panel-subtitle">搜索条件</span>
						</div>
						<ul class="list-unstyled search-condition">
							<li>
								<dl class="condition-group">
									<dt class="condition-field">时长：</dt>
									<dd class="condition-item-group">
									  	<a class="condition-item text-primary" href="">全部</a>
									  	<a class="condition-item text-gray-dark" href="">长(30分钟以上)</a>
									  	<a class="condition-item text-gray-dark" href="">中（10到30分钟）</a>
									  	<a class="condition-item text-gray-dark" href="">短（0到10分钟）</a>
									</dd>
								</dl>
								<dl class="condition-group">
									<dt class="condition-field">视频时间：</dt>
									    <dd class="condition-item-group">
									  	    <a class="condition-item" href="">全部</a>
									  	    <a class="condition-item text-gray-dark" href="">一周内</a>
									  	    <a class="condition-item text-gray-dark" href="">一月内</a>
									  	    <a class="condition-item text-gray-dark" href="">一年内</a>
									    </dd>
								</dl>
								<dl class="condition-group">
									<dt class="condition-field">视频来源：</dt>
									<dd class="condition-item-group">
									  	<a class="condition-item" href="">全部</a>
									  	<a class="condition-item text-gray-dark" href="">白云机场</a>
									  	<a class="condition-item text-gray-dark" href="">南沙港</a>
									  	<a class="condition-item text-gray-dark" href="">水上保税仓</a>
									</dd>
								</dl>
							</li>
						</ul>
					</div>
				</div>
			</div>


		</div>
	</div>

app/views/resources/edit.html.erb
<h1>Editing Resource</h1>

<%= render 'form', resource: @resource %>

<%= link_to 'Show', @resource %> |
<%= link_to 'Back', resources_path %>

app/views/resources/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Resources</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @resources.each do |resource| %>
      <tr>
        <td><%= link_to 'Show', resource %></td>
        <td><%= link_to 'Edit', edit_resource_path(resource) %></td>
        <td><%= link_to 'Destroy', resource, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Resource', new_resource_path %>

app/views/resources/new.html.erb
<h1>New Resource</h1>

<%= render 'form', resource: @resource %>

<%= link_to 'Back', resources_path %>

app/views/resources/search.html.erb
<%= render 'bread_nav', resource: @resource %>
  <!-- 路径导航 end -->
 <%= render 'leftside', resource: @resource %>
 <!-- 右侧内容 -->
 <% case @search_type 
    when "infomation" %>
      	<%= render 'rightside_infomation', resource: @resource  %>
 <% when "doc" %>
      	<%= render 'rightside_doc', resource: @resource  %>
 <% when "image" %>
 	  	<%= render 'rightside_image', resource: @resource  %>
 <% when "video" %>
 		<%= render 'rightside_video', resource: @resource  %>
 <% else 
    end %>


   
 
 

app/views/resources/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_resource_path(@resource) %> |
<%= link_to 'Back', resources_path %>

app/views/todomvc/angular2_es2015.html.erb
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>Angular2 with ES2015 • TodoMVC</title>
    <%= stylesheet_pack_tag 'todomvc-angular2-es2015' %>
</head>
<body>
    <todo-app></todo-app>

    <%= javascript_pack_tag 'todomvc-angular2-es2015' %>
</body>
</html>

app/views/vue_templates/_modal.html.erb
<script type="text/x-template" id="modal-template">
  <transition name="modal">
    <div class="vue-modal-mask">
      <div class="vue-modal-wrapper">
        <div class="vue-modal-container" v-bind:style="{width: modalWidth}">

          <div class="vue-modal-header">
            <slot name="header">
              default header
            </slot>
          </div>

          <div class="vue-modal-body">
            <slot name="body">
            </slot>
          </div>

          <div class="vue-modal-footer">
            <slot name="footer">
              <button class="vue-modal-default-button" @click="$emit('close')">
                OK
              </button>
            </slot>
          </div>
          <div class="clearfix">
          </div>
        </div>
      </div>
    </div>
  </transition>
</script>
<%= content_for :stylesheets  do%>
<style>
.vue-modal-mask {
  position: fixed;
  z-index: 9998;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
  background-color: rgba(0, 0, 0, .5);
  display: table;
  transition: opacity .1s ease;
}

.vue-modal-wrapper {
  display: table-cell;
  vertical-align: middle;
}

.vue-modal-container {
  margin: 0px auto;
  padding: 20px 30px;
  background-color: #fff;
  border-radius: 2px;
  box-shadow: 0 2px 8px rgba(0, 0, 0, .33);
  transition: all .1s ease;
  font-family: Helvetica, Arial, sans-serif;
}

.vue-modal-header h3 {
  margin-top: 0;
  color: #42b983;
}

.vue-modal-body {
  margin: 20px 0;
}

.vue-modal-default-button {
  float: right;
}

/*
* The following styles are auto-applied to elements with
* transition="modal" when their visibility is toggled
* by Vue.js.
*
* You can easily play with the modal transition by editing
* these styles.
*/

.vue-modal-enter {
  opacity: 0;
}

.vue-modal-leave-active {
  opacity: 0;
}

.vue-modal-enter .vue-modal-container,
.vue-modal-leave-active .vue-modal-container {
  -webkit-transform: scale(1.1);
  transform: scale(1.1);
}
</style>
<% end %>