config/routes.rb
Rails.application.routes.draw do

  resources :tactic_covers
  root 'dashboard#index'

  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }

  resources :calllists  do
    collection do
      get :export
      post :read_from_excel
      post :save_from_json
      get :load_note_options
      get :load_date_options
      get :load_batch_options
    end
  end

  resources :call_analyse_savers do
    collection do
      get :default
    end
  end

  resources :cases do
    collection do
      get :search
    end
  end

  resources :dashboard

  resources :extra_tasks do
    member do
      get :jump_to_execute
      get :jump_to_show
      get :jump_to_bind
    end
  end

  resources :image_views, only: [:index]

  resources :position_decisions

  resources :resources do
    collection do
      get :search
    end
  end

  resources :suspects

  resources :suspects_teams

  resources :tactics do
    member do
      get :get_tactic_tasks
      post :persist_tasks
      get :progress
      get :edit_covers
    end
  end

  resources :tactic_tasks

  resources :tools do
    collection do
      get :home
      get :add_info
      get :add_manual
      get :rlat
      get :rlat_details
    end
  end

  post 'users/search', to: 'users/users#search'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/calllist.rb
require 'roo'

class Calllist < ApplicationRecord

  #从文件读取数据,不作处理直接返回json
  def self.read(file)
    spread_sheets = Roo::Spreadsheet.open(file)
    sheets_names = spread_sheets.sheets
    sheets = sheets_names.map{|name| {:name=>name,:rows => spread_sheets.sheet(name).map{|rows| rows}}}
    #[{:name=>"name",:rows=>[[row]...],[],[]]
    return sheets
  end

end

app/controllers/calllists_controller.rb
class CalllistsController < ApplicationController
  before_action :login_required, :only => [:index,:show,:new,:edit,:create]
  #protect_from_forgery :except => :export
  protect_from_forgery :except => :process_excel

  before_action :set_calllist, only: [:show, :edit, :update, :destroy]
  #skip_before_action :verify_authenticity_token

  #直接从数据库中导出calllist的数据(导出为{link:[{}...],node:[{}...]}的格式)
  #若没有指定batch(批次)参数,则导出全部
  def export
    filters = params["filters"]
    if filters.present?
      origin = Calllist.all
      origin = origin.where(:note => filters["note_filters"].split(",")) if filters["note_filters"].present?
      origin = origin.where(:created_at => filters["date_filters"].split(",")) if filters["date_filters"].present?
      origin = origin.where(:batch => filters["batch_filters"].split(",")) if filters["batch_filters"].present?
      lite = origin.select{|c| !c.from_num.nil? and !c.to_num.nil?}
                   .map{ |c| {:from_num => c.from_num, :to_num => c.to_num }}
    else
      origin = Calllist.all
      lite = origin.select{|c| !c.from_num.nil? and !c.to_num.nil?}
                   .map{ |c| {:from_num => c.from_num, :to_num => c.to_num }}
    end
    render :json => {:msg=>"calllist was successfully exported!",:success=>true,:data=>lite}
  end

  #从前端上传的excel文件中读取数据而不保存,并且按照原始的json格式返回({name1:value1,name2:value2,...})
  def read_from_excel
    data = Calllist.read(params[:file])
    render :json => {:msg => "file read successfully!",:success =>true,:data => data}
  end

  def save_from_json
    array = params[:data].values
    note = params[:note]
    batch =  current_user.id.to_s + Time.now.strftime('_%Y_%m_%d_') + Time.now.to_i.to_s
    if current_user
      Calllist.transaction do
        array.each do |row|
          row['batch'] = batch
          row['note'] = note
          Calllist.create!(row)
        end
      end
      render :json => {:msg =>"data saved successfully!",:success =>true,:batch => batch,:note => note}
    else
      render :json => {:msg =>"failed to get user info,you need to login!",:success =>false}
    end
  end

  # GET /calllists
  # GET /calllists.json
  def index
    @calllists = Calllist.all
  end

  # GET /calllists/1
  # GET /calllists/1.json
  def show
  end

  # GET /calllists/new
  def new
    @calllist = Calllist.new
  end

  # GET /calllists/1/edit
  def edit
  end

  # POST /calllists
  # POST /calllists.json
  def create
    @calllist = Calllist.new(calllist_params)

    respond_to do |format|
      if @calllist.save
        format.html { redirect_to @calllist, notice: 'Calllist was successfully created.' }
        format.json { render :show, status: :created, location: @calllist }
      else
        format.html { render :new }
        format.json { render json: @calllist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /calllists/1
  # PATCH/PUT /calllists/1.json
  def update
    respond_to do |format|
      if @calllist.update(calllist_params)
        format.html { redirect_to @calllist, notice: 'Calllist was successfully updated.' }
        format.json { render :show, status: :ok, location: @calllist }
      else
        format.html { render :edit }
        format.json { render json: @calllist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /calllists/1
  # DELETE /calllists/1.json
  def destroy
    @calllist.destroy
    respond_to do |format|
      format.html { redirect_to calllists_url, notice: 'Calllist was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def load_note_options
    note = Calllist.select('DISTINCT(note), created_at').order('created_at desc').select{|x| x.note.present?}.map{|x| x.note}
    render :json =>{:msg => "数据获取成功", :success => true, :type => 'note', :data => note}
  end

  def load_date_options
    date = Calllist.select('DISTINCT(created_at)').order('created_at desc').select{|x| x.created_at.present?}.map{|x| x.created_at}
    render :json =>{:msg => "数据获取成功", :success => true, :type => 'date', :data => date}
  end

  def load_batch_options
    batch = Calllist.select('DISTINCT(batch), created_at').order('created_at desc').select{|x| x.batch.present?}.map{|x| x.batch}
    render :json =>{:msg => "数据获取成功", :success => true, :type => 'batch', :data => batch}
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_calllist
      @calllist = Calllist.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def calllist_params
      params.require(:calllist).permit(:from_num, :to_num)
    end
end

app/helpers/calllists_helper.rb
module CalllistsHelper
end

app/views/calllists/_form.html.erb
<%= form_with(model: calllist, local: true) do |form| %>
  <% if calllist.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(calllist.errors.count, "error") %> prohibited this calllist from being saved:</h2>

      <ul>
      <% calllist.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :from_num %>
    <%= form.text_field :from_num, id: :calllist_from_num %>
  </div>

  <div class="field">
    <%= form.label :to_num %>
    <%= form.text_field :to_num, id: :calllist_to_num %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/calllists/edit.html.erb
<h1>Editing Calllist</h1>

<%= render 'form', calllist: @calllist %>

<%= link_to 'Show', @calllist %> |
<%= link_to 'Back', calllists_path %>

app/views/calllists/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Calllists</h1>

<table>
  <thead>
    <tr>
      <th>From num</th>
      <th>To num</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @calllists.each do |calllist| %>
      <tr>
        <td><%= calllist.from_num %></td>
        <td><%= calllist.to_num %></td>
        <td><%= link_to 'Show', calllist %></td>
        <td><%= link_to 'Edit', edit_calllist_path(calllist) %></td>
        <td><%= link_to 'Destroy', calllist, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Calllist', new_calllist_path %>

app/views/calllists/new.html.erb
<h1>New Calllist</h1>

<%= render 'form', calllist: @calllist %>

<%= link_to 'Back', calllists_path %>

app/views/calllists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>From num:</strong>
  <%= @calllist.from_num %>
</p>

<p>
  <strong>To num:</strong>
  <%= @calllist.to_num %>
</p>

<%= link_to 'Edit', edit_calllist_path(@calllist) %> |
<%= link_to 'Back', calllists_path %>